import pandas as pd

'''
DATA
'''
# DATANAME = "p01_15.291.tsp"
# DATANAME = "gr17.2085.tsp"
# DATANAME = "five.19.tsp"
# DATANAME = "br17.39.atsp"
DATANAME = "att48.33523.tsp"

DATA = pd.read_csv("data/{}".format(DATANAME),header=None,delim_whitespace=True)
TARGET = int(DATANAME.split(".")[1])

NUMBER_INDIVIDU = len(DATA)

'''
PROBLEME
'''
# PROBLEM = "MAX_ONE"
PROBLEM = "TSP"

'''
Selection
'''
# SELECTION = "Tournament"
# SELECTION = "Roulette_Wheel"
SELECTION = "Rank_Based"

'''
REPLACEMENT
'''
# REPLACEMENT_STRATEGIE = "Generational"
REPLACEMENT_STRATEGIE = "Steady_State"
# REPLACEMENT_STRATEGIE = "Mixte"
#18.240
'''
CONSTANT - GLOBAL
'''
SIZE_POPULATION = 80
NUMBER_SOLUTION_REPLACE = 20
NUMBER_FAMILY = int(NUMBER_SOLUTION_REPLACE / 2)
NUMBER_MAX_GENERATION = 100000
MUTATION = 55
ELITISM = 3
INDICE_CROSSOVER = 22

'''
CONSTANT - TOURNAMENT
'''
NUMBER_FINALIST = 5

'''
CONSTANT - RANK_BASED
'''
SELECTION_PRESSURE = 1

'''
CONSTANT - MAX_ONE
'''
SIZE_BINARY = 1000
